apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-statefulSet
spec:
  serviceName: mongodb # Add the serviceName property here
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb-container
          image: mongo:latest
          ports:
            - containerPort: 27017