apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-statefulSet
spec:
  serviceName: redis # Add the serviceName property here
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis-container
          image: redis:latest
          ports:
            - containerPort: 6379